# Generated by Django 3.2.7 on 2021-09-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.IntegerField(choices=[(1, 'level1'), (2, 'level2'), (3, 'level3')]),
        ),
    ]
